version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: 'sqlserver'
    container_name: airport_sqlserver
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: "AvS#a1s45s"
    volumes:
      - c:\dados\volumes\mssql:/var/opt/mssql3
    ports:
      - '11433:1433'    
    expose:
      - 1433

  airport.routecalculator.api:
    image: ${DOCKER_REGISTRY-}airportroutecalculatorapi
    build:
      context: .
      dockerfile: Airport.RouteCalculator.API/Dockerfile
    container_name: airport_routecalculatorapi
    depends_on:
      - sqlserver